name: build
on:
  pull_request:

env:
  CACHE_VERSION: 1
  PRE_COMMIT_CACHE: ~/.cache/pre-commit

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        python: ['3.9', '3.10', '3.11', '3.12', '3.13']
        os: [ubuntu-latest, windows-latest, macos-13, macos-latest]
        tox_env: ["py"]
        include:
          - python: '3.13'
            os: ubuntu-latest
            tox_env: 'lint'
        exclude:
          - python: '3.9'
            os: macos-latest
          - python: '3.10'
            os: macos-latest

    steps:
    - name: Set git to not change EoL
      if: runner.os == 'Windows'
      run: |
        git config --global core.autocrlf false
    - name: Cache pre-commit packages
      id: cache-pre-commit
      uses: actions/cache@v4
      with:
        path: ${{ env.PRE_COMMIT_CACHE }}
        key: ${{ runner.os }}-${{ runner.arch }}-py${{ matrix.python }}-pre-commit
    - uses: actions/checkout@v4.1.2
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v5.0.0
      with:
        python-version: ${{ matrix.python }}
        architecture: 'x64'
        cache: 'pip'
    - name: install dependencies
      run: |
        pip install .[test]
    - name: Test
      run: tox -e ${{ matrix.tox_env }} -v
